# Oh yeah!
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false

# Node 18 binaries require glibc >= 2.28
dist: focal

node_js:
  - 'stable'
  - '16'
  - '14'

# Set INIT_CWD for Husky due to Npm 7 not including it.
before_install:
  - export INIT_CWD="$(pwd)"

# Lint errors should trigger a failure.
before_script:
  - npm run lint
  - npm run build

# Runs the coverage script (which runs the tests)
script: npm run cover

# Code coverage
after_success:
  - npm run coveralls
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
